server {
    listen ${PORT};
    server_name _;

    root /app/public;
    index anomalies.html;

    location /anomalies-assets/ {
        rewrite ^/anomalies-assets/(.*)$ /$1 last;
    }

    location /anomalies-backend/ {
        proxy_pass ${ANOMALIES_BACKEND_URL}/;
        proxy_set_header Host $host;
    }
}
