server {
    listen ${PORT};
    server_name _;

    root /app/public;
    index index.html;

    location /anomalies-backend/ {
        proxy_pass ${ANOMALIES_BACKEND_URL}/;
        proxy_set_header Host $host;
    }
}
