services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
      - ./ai-services/entrypoint.sh:/ai-services/entrypoint.sh
      - ./ai-services/healthcheck.sh:/ai-services/healthcheck.sh
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/ai-services/entrypoint.sh"]
    environment:
      # Any models you want to use must be listed here, to ensure they are installed on the container
      OLLAMA_PULL_MODELS: qwen2.5:0.5b llama3.1:8b qwen2.5:3b
    healthcheck:
      test: ["CMD", "/bin/sh", "/ai-services/healthcheck.sh"]
      # Probe every 5s during the first minute, then every 30s for an hour
      # TODO change these params because it's messing with the health of the container
      start_period: 60s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 120

  shared-frontend:
    build: ./shared/frontend
    container_name: shared-frontend
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      TRANSACTIONS_FRONTEND_URL: http://transactions-frontend:3001
      ANOMALIES_FRONTEND_URL: http://anomalies-frontend:3004
      SAVINGS_FRONTEND_URL: http://savings-frontend:3002
      BILLS_FRONTEND_URL: http://bills-frontend:80
    depends_on:
      - transactions-frontend
      - anomalies-frontend
      - savings-frontend
      - bills-frontend

  transactions-frontend:
    build: ./janelle/frontend
    container_name: transactions-frontend
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    depends_on:
      - transactions-backend
  transactions-backend:
    build: ./janelle/backend
    container_name: transactions-backend
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
      PORT: 5001
      TRANSACTIONS_DB_URL: http://transactions-db:6001
      DATABASE_TIMEOUT_SECONDS: 20
    depends_on:
      - transactions-db
  transactions-db:
    build: ./janelle/database
    container_name: transactions-db
    ports:
      - "6001:6001"
    environment:
      FLASK_ENV: production
      PORT: 6001
      DB_PATH: /app/data/transactions.db
    volumes:
      - transactions_data:/app/data

  bills-frontend:
    build: ./sophia/frontend
    container_name: bills-frontend
    ports:
      - "3005:80"
    depends_on:
      - bills-backend
  bills-backend:
    build: ./sophia/backend
    container_name: bills-backend
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      BILLS_DB_API_URL: http://bills-db:6005
      FRONTEND_ORIGIN: http://localhost:3005
      OLLAMA_URL: http://ollama:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bills-db
      - ollama
  bills-db:
    build: ./sophia/database
    container_name: bills-db
    ports:
      - "6005:6005"
    environment:
      PORT: 6005
      DB_PATH: /data/bills.db
    volumes:
      - bills_data:/data

  anomalies-frontend:
    build: ./aiden/frontend
    container_name: anomalies-frontend
    ports:
      - 3004:3004
    environment:
      PORT: 3004
      ANOMALIES_BACKEND_URL: http://anomalies-backend:5004
    depends_on:
      - anomalies-backend
  anomalies-backend:
    build:
      dockerfile: ./aiden/backend/Dockerfile
    container_name: anomalies-backend
    ports:
      - 5004:5004
    environment:
      FLASK_ENV: production
      PORT: 5004
      ANOMALIES_DB_URL: http://anomalies-db:6004/anomalies
      TRANSACTIONS_DB_URL: http://transactions-db:6001
      OLLAMA_URL: http://ollama:11434/v1
      OLLAMA_MODEL: qwen2.5:3b
    depends_on:
      anomalies-db:
        condition: service_started
      ollama:
        condition: service_healthy
  anomalies-db:
    build:
      dockerfile: ./aiden/database/Dockerfile
    container_name: anomalies-db
    ports:
      - 6004:6004
    volumes:
      - anomalies_data:/app/data
    environment:
      FLASK_ENV: production
      PORT: 6004
      DB_PATH: /app/data/anomalies.db

  savings-db:
    build: 
      dockerfile: ./david/database/Dockerfile
    container_name: savings-db
    ports:
      - 6002:6002
    environment:
      FLASK_ENV: production
      PORT: 6002
      DB_PATH: /app/data/savings.db
    volumes:
      - savings_data:/app/data
  savings-backend:
    build: 
      dockerfile: ./david/backend/Dockerfile
    container_name: savings-backend
    ports:
      - 5002:5002
    environment:
      FLASK_ENV: production
      PORT: 5002
      DB_URL: http://savings-db:6002
    depends_on:
      - savings-db
  savings-frontend:
    build: ./david/frontend/
    container_name: savings-frontend
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      BACKEND_URL: http://savings-backend:5002
    depends_on:
      - savings-backend

volumes:
  ollama_data:
  transactions_data:
  bills_data:
  anomalies_data:
  savings_data:
