services:
  bills-frontend:
    build: ./sophia/frontend
    container_name: bills-frontend
    ports:
      - "3005:80"
    depends_on:
      - bills-backend
  bills-backend:
    build: ./sophia/backend
    container_name: bills-backend
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      BILLS_DB_API_URL: http://bills-db:6005
      OLLAMA_URL: http://host.docker.internal:11434
      DRAFT_MODEL: llama3.1:8b
      CHAT_MODEL: qwen2.5:0.5b
      DEMO_TODAY: "2026-08-20"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bills-db
  bills-db:
    build: ./sophia/database
    container_name: bills-db
    ports:
      - "6005:6005"
    environment:
      PORT: 6005
      DB_PATH: /data/bills.db
    volumes:
      - bills_data:/data

  anomalies-frontend:
    build: ./aiden/frontend
    container_name: anomalies-frontend
    ports:
      - 3004:3004
    environment:
      NGINX_PORT: 3004
    depends_on:
      - anomalies-backend
  anomalies-backend:
    build: ./aiden/backend
    container_name: anomalies-backend
    ports:
      - 5004:5004
    environment:
      FLASK_ENV: production
      PORT: 5004
      ANOMALIES_DB_URL: http://anomalies-db:6004
    depends_on:
      - anomalies-db
  anomalies-db:
    build:
      dockerfile: ./aiden/database/Dockerfile
    container_name: anomalies-db
    ports:
      - 6004:6004
    volumes:
      - anomalies_data:/app/data
    environment:
      FLASK_ENV: production
      PORT: 6004
      DB_PATH: /app/data/anomalies.db

  savings-db:
    build: ./david/database
    container_name: savings-db
    ports:
      - "6002:6002"
    environment:
      FLASK_ENV: production
      PORT: 6002
      DB_PATH: /app/data/savings.db
    volumes:
      - savings_data:/data

volumes:
  bills_data:
  anomalies_data:
  savings_data:
