services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  bills-frontend:
    build: ./sophia/frontend
    container_name: bills-frontend
    ports:
      - "3005:80"
    depends_on:
      - bills-backend
  bills-backend:
    build: ./sophia/backend
    container_name: bills-backend
    ports:
      - "5005:5005"
    environment:
      PORT: 5005
      BILLS_DB_API_URL: http://bills-db:6005
      FRONTEND_ORIGIN: http://localhost:3005
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bills-db
  bills-db:
    build: ./sophia/database
    container_name: bills-db
    ports:
      - "6005:6005"
    environment:
      PORT: 6005
      DB_PATH: /data/bills.db
    volumes:
      - bills_data:/data

  anomalies-frontend:
    build: ./aiden/frontend
    container_name: anomalies-frontend
    ports:
      - 3004:3004
    environment:
      PORT: 3004
      ANOMALIES_BACKEND_URL: http://anomalies-backend:5004
    depends_on:
      - anomalies-backend
  anomalies-backend:
    build:
      dockerfile: ./aiden/backend/Dockerfile
    container_name: anomalies-backend
    ports:
      - 5004:5004
    environment:
      FLASK_ENV: production
      PORT: 5004
      ANOMALIES_DB_URL: http://anomalies-db:6004/anomalies
      OLLAMA_URL: http://ollama:11434/v1
      OLLAMA_IMPLEMENTATION_MODEL: qwen2.5:0.5b
      OLLAMA_REVIEW_MODEL: llama3.1:8b
    depends_on:
      - anomalies-db
      - ollama
  anomalies-db:
    build:
      dockerfile: ./aiden/database/Dockerfile
    container_name: anomalies-db
    ports:
      - 6004:6004
    volumes:
      - anomalies_data:/app/data
    environment:
      FLASK_ENV: production
      PORT: 6004
      DB_PATH: /app/data/anomalies.db

  savings-db:
    build: 
      dockerfile: ./david/database/Dockerfile
    container_name: savings-db
    ports:
      - 6002:6002
    environment:
      FLASK_ENV: production
      PORT: 6002
      DB_PATH: /app/data/savings.db
    volumes:
      - savings_data:/app/data
  savings-backend:
    build: 
      dockerfile: ./david/backend/Dockerfile
    container_name: savings-backend
    ports:
      - 5002:5002
    environment:
      FLASK_ENV: production
      PORT: 5002
      DB_URL: http://savings-db:6002
    depends_on:
      - savings-db
  savings-frontend:
    build: ./david/frontend/
    container_name: savings-frontend
    ports:
      - 3002:3002
    environment:
      PORT: 3002
      BACKEND_URL: http://savings-backend:5002
    depends_on:
      - savings-backend

volumes:
  ollama_data:
  bills_data:
  anomalies_data:
  savings_data:
