server {
    listen ${PORT};
    server_name _;

    root /app/public;
    index index.html;

    proxy_set_header Host $host;

    # Discover and proxy the individual service frontends.
    location /anomalies-frontend/ {
        proxy_pass ${ANOMALIES_FRONTEND_URL}/;
    }

    location /transactions-frontend/ {
        proxy_pass ${TRANSACTIONS_FRONTEND_URL}/;
    }

    location /savings-frontend/ {
        proxy_pass ${SAVINGS_FRONTEND_URL}/;
    }

    location /bills-frontend/ {
        proxy_pass ${BILLS_FRONTEND_URL}/;
    }

    # The shared frontend never directly communicates with any of the backends, however
    # it still needs to know the backend URL paths to correctly forward requests from the UIs.
    # Note that it doesn't know what the backend URLs are, that information is owned by the
    # individual frontends.
    location /anomalies-backend/ {
        proxy_pass ${ANOMALIES_FRONTEND_URL};
    }

    location /transactions-backend/ {
        proxy_pass ${TRANSACTIONS_FRONTEND_URL};
    }

    location /savings-backend/ {
        proxy_pass ${SAVINGS_FRONTEND_URL};
    }

    location /bills-backend/ {
        proxy_pass ${BILLS_FRONTEND_URL};
    }
}
