server {
    listen ${PORT};
    server_name _;

    root /app/public;
    index index.html;

    location /budgets-backend/ {
        proxy_pass ${BUDGETS_BACKEND_URL}/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
